apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: "rabbitmq:4.1.0-management-alpine"

  # This tells the operator to use existing secret instead of generating one
  secretBackend:
    externalSecret:
      name: rabbitmq-secret

  rabbitmq:
    additionalConfig: |
      management.path_prefix = /rabbitmq
      # Enforce data replication to Quorum Queues
      default_queue_type = quorum

  persistence:
    storageClassName: ebs-sc # must need to match the storage/ manifest
    storage: 10Gi

  override:
    statefulSet:
      spec:
        # Auto cleanup disks
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Delete

        template:
          spec:
            # give RabbitMQ time to move data before the node is hard-deleted
            terminationGracePeriodSeconds: 300

            containers:
              - name: rabbitmq
                # Wait for data sync before killing
                lifecycle:
                  preStop:
                    exec:
                      command: [ "/bin/sh", "-c", "rabbitmq-queues check_if_node_is_quorum_critical" ]

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - rabbitmq
          topologyKey: "kubernetes.io/hostname"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi