apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: "rabbitmq:4.1.0-management-alpine"

  # This tells the operator to use existing secret instead of generating one
  secretBackend:
    externalSecret:
      name: rabbitmq-secret

  rabbitmq:
    additionalConfig: |
      management.path_prefix = /rabbitmq

  persistence:
    storageClassName: ebs-sc # Ensure this matches your storage/ manifest
    storage: 10Gi

  override:
    statefulSet:
      spec:
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Delete

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - rabbitmq
          topologyKey: "kubernetes.io/hostname"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi