name: k3s-worker-and-asg
description: Auto Scaler Group, Worker Node Templates
runtime:
  name: python
  options:
    toolchain: pip
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python